name: Tests for TelegramStatusBot

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest
#      - uses: "finnp/create-file-action@master"
#        env:
#          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#          FILE_NAME: "src/config.py"
#          FILE_DATA: "BOT_TOKEN = '${{ secrets.BOT_TOKEN }}'"
      - name: Echo
        run:
          echo 'BOT_TOKEN = \'${{ secrets.BOT_TOKEN }}\'' >> src/config.py
      - name: Test with pytest
        run: |
          python -m pytest tests/test_handlers.py